<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="SearchResults.aspx.cs" Inherits="Esondage2018.View.SearchResults" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Test recherche</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/iconic/css/material-design-iconic-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="css/util.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="../Content/Styles.css" />
<!--===============================================================================================-->

    <script type="text/javascript" src="vendor/jquery/jquery-3.2.1.min.js"></script>
</head>
<body>
    <form id="form1" runat="server">
        <header class="sthead">
            <div class="lhead">
                <a href="http://localhost:54719/View/Index.aspx" title="makeSurvey, add an user, Home" /><img class="stlogo" alt="flocalhost:54719/View/Index.aspx" src="../Picture/logo.png"/></a>
            </div>

            <div class="rhead">
        	    <div id="recherche" > <!-- method="post" -->
                    <asp:TextBox ID="searchField" runat="server" class="sinput" placeholder="User or poll ..."></asp:TextBox>
                    <asp:Button ID="search" runat="server" class="loupe" PostBackUrl="~/View/SearchResults.aspx" />
        	    </div>

                <asp:ImageButton  ID="log" runat="server" class="rslogo" ImageUrl="~/Picture/log.png" OnClick="log_Click" />
                <a id="mngRsh" runat="server" href="http://google.com" title="Manage user and polls"><img class="rslogo" alt="google.com" src="../Picture/wrench.png"/></a>
                <a href="http://google.com" title="Profile"><img class="rslogo" alt="google.com" src="../Picture/user.png"/></a>
                <a href="http://facebook.com" title="Like our Facebook page"><img class="rslogo" alt="facebook.com" src="../Picture/facebook_logo.png"/></a>
                <a href="http://twitter.com" title="Follow us on Twitter"><img class="rslogo" alt="twitter.com" src="../Picture/twitter_logo.png"/></a>
            </div>
        </header>
        <section id="scRsh" class="bdrLayout center">
            <article id="artResRsh" class="artLayout center">
                <div id="posTitleRes">
                    <asp:Label ID="lblSearch" runat="server" class="pageTitle"></asp:Label>
                </div>
                <div id="posTitleUsrRes">
                    <asp:Label ID="titlUsreRsh" runat="server" class="pageSubTitle">Users</asp:Label>
                </div>
                <div class="gridSpaceRsh"> <!--AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"--> 
                    <asp:GridView ID="GridView1" runat="server" class="dataRes center" AutoGenerateColumns="False"
                    emptydatatext="No data available.">                     

                        <Columns>
                            <asp:BoundField DataField="Id" HeaderText="Id" SortExpression="Id"/>
                            <asp:BoundField DataField="TypeUser" HeaderText="TypeUser" SortExpression="TypeUser"/>
                            <asp:BoundField DataField="email" HeaderText="email" SortExpression="email"/>
                            <asp:BoundField DataField="pass" HeaderText="pass" SortExpression="pass"/>
                            <asp:BoundField DataField="nom" HeaderText="nom" SortExpression="nom"/>
                        </Columns>

                        <HeaderStyle CssClass="headTabRsh" />
                        <RowStyle CssClass="center bodyTabRsh" />
                    </asp:GridView>     
                </div>

                <div id="posTitleUsrRes">
                    <asp:Label ID="titleUsrRsh" runat="server" class="pageSubTitle">Polls</asp:Label>
                </div>
                <div class="gridSpaceRsh"> <!-- AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"> -->
                    <asp:GridView ID="GridView2" runat="server" class="dataRes center" DataKeyNames="Id" 
                    PageSize="11" emptydatatext="No data available." AutoGenerateColumns="False" >
                        <Columns>
                            <asp:BoundField DataField="question" HeaderText="question" SortExpression="question"/>
                            <asp:BoundField DataField="Id" HeaderText="Id" SortExpression="Id"/>
                            <asp:ButtonField Text="Voir" CommandName="Select"/>
                        </Columns>

                        <HeaderStyle CssClass="headTabRsh" />
                        <RowStyle CssClass="center bodyTabRsh" />
                    </asp:GridView>
                </div>
            </article>
        </section>

    </form>
</body>
</html>
